### ISSUE TITLE
Error on plugin

### ISSUE THREAD

**Issue by JustOneMoreBlock** [cartman-2000/PlayerInfoLib#1]
Hello,

Downloaded the latest version and I received this error.
http://pastebin.com/raw/PL0MpxJ7

Kind Regards,
Cory

**Comment by cartman-2000** [comment]
Not an issue with my plugin, by the error trace, you have a syntax error in rocket's Commands.config.xml file, you should delete this file and let rocket recreate it.

**Comment by JustOneMoreBlock** [comment]
Yep, my bad.

Issued Closed.
