### ISSUE TITLE
Possibly some Minor Changes

### ISSUE THREAD

**Issue by JustOneMoreBlock** [cartman-2000/PlayerInfoLib#2]
Hello,

After installing your plugin, it does work and does what we want. However, using the /investigate command shows the way to much information. As mainly, we only need it for the SteamID64. Although, it searches through the whole database.

http://i.imgur.com/dMkNUTG.png

It should basically;

Let's say; I search for pete.

It will see if there is a pete on the server, grab that player name/SteamID64 and pull only that pete's information.

I still plan on keeping your plugin as it's a great informational tool and I tried switching back to rocket's investigate as our staff can hardly use it in its current situation as they have to scroll up fast enough as there is too much information being displayed.

However, providing the permission to rocket and removing yours provide "no permission" or "command not found". Upon looking into the commands file, I noticed this was disabled, and it's clearly your plugin overriding the plugin regardless.

```
    <Command Name="investigate" Enabled="false" Priority="Normal">Rocket.Unturned.Commands.CommandInvestigate/investigate</Command>
```

Solutions:

In the config file, possibly add <ChatFormat> tag and do something like this;

```
<ChatFormat>Server: %ServerInstance% - %SteamName% - %SteamID% - %IP% - Last Seen: %Seen% - TT: %TotalTimePlayed%</ChatFormat>
```

Notes:
The purpose of %ServerInstance% is because my PvE3 is "ServerID 1" this can be confusing. Granted, I could easily take down all the servers and do quick MySQL query updates to fix that.

```
<DisplayMode>1</DisplayMode>

1 = Simple (ChatFormat)
2 = Advanced (Current)
```

I plan on making a web interface for this as it would be easier for my staff. :)

**Comment by cartman-2000** [comment]
The Investigate command in this plugin functions more like the original one did in Unturned prior to nelson removing the player data file from the game. The current one in Rocket can only return a steam id for a player if the player is currently on the server, but as it has no stored player data to access, so it can only show the Steam ID of a player that is still on the server. The order of the list is prioritized with the most current last seen first, so if the player that you're searching for has been on the server recently, they should be near the top of the list.

It should be possible to disable the Investigate command in my plugin. You should be able to disable it by setting mine to a low priority, and setting it to false, then enabling Rocket's Investigate command.

Something like a custom format could be done, although problematic, as line wrapping in rocket is buggy and can cut text off if it has to split the lines across multiple messages. I could also add a config option to fetch from the current server only, not all that have been added to the database.

**Comment by JustOneMoreBlock** [comment]
- Don't think it works.

- Tried this and doesn't work. :(

- That be great!

Take your time, there is no rush.
