### ISSUE TITLE
Update your MySQL Lib

### ISSUE THREAD

**Issue by JustOneMoreBlock** [cartman-2000/PlayerInfoLib#3]
Your current MySQL Library you provide does not work with other plugins.

I've copied the MySQL Library from here and works fine for all plugins.
https://ci.dev.rocketmod.net/view/3)%20Adopted%20Plugins/job/ZaupShop/lastSuccessfulBuild/artifact/bin/Release/ZaupShop.zip

**Comment by cartman-2000** [comment]
The most recent upload of the plugin on the dev page has the newer MySQL libs.

**Comment by RechtVH** [comment]
Good Day cartman-2000 , absolutely great plugin, only want to know if it can be updated to work with MYSQL 5.7 and on. there are an issue or two with the sql columns. 

Exception in PlayerInfoLib: MySql.Data.MySqlClient.MySqlException: Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'g.ServerID

Now although some features of the plugin work some do not as data is not getting written to the DB  for example total play time on server etc.

Thanks again and wish you well. this is truly one of the best plugins and if you find it in you to continue this plugin please update it and we would be eternally grateful.
