### ISSUE TITLE
Database version not found

### ISSUE THREAD

**Issue by KamoiChikubi** [cartman-2000/PlayerInfoLib#4]
After the new update, the plugin keeps giving this error on start:

Error: Database version number not found.
PlayerInfoLib >> There was in issue loading the plugin, please check your config

It isn't working at all for me.

**Comment by cartman-2000** [comment]
Did you by any chance wipe the database tables? if you also wiped the config table that would delete the database version row, which would cause the plugin to fail to load.

If that was the case, you should be able to get it working again by running this query. The playerinfo part of "playerinfo_config" would be set to what you have it set to in the plugin's config.
INSERT INTO `playerinfo_config` (`key`, `value`) VALUES ('version', '3');

**Comment by KamoiChikubi** [comment]
Yes I did empty the tables but didn't delete them. Deleting them has fixed this error. Thank you so much!
